name: Update public-suffix-list.dat and rdap-servers-iana.json

on:
  schedule:
    - cron: "33 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Download files
        run: |
          curl -fsSL "https://publicsuffix.org/list/public_suffix_list.dat" -o src/data/public-suffix-list.dat
          curl -fsSL "https://data.iana.org/rdap/dns.json" -o src/data/rdap-servers-iana.json

      - name: Commit and push
        run: |
          psl_updated=$(git diff --quiet src/data/public-suffix-list.dat || echo "true")
          rdap_updated=$(git diff --quiet src/data/rdap-servers-iana.json || echo "true")

          if $psl_updated || $rdap_updated; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            base_tag="v$(date -u +%Y.%-m.%-d)"
            tag="${base_tag}"
            i=1
            while git rev-parse "${tag}" >/dev/null 2>&1; do
              tag="${base_tag}+${i}"
              ((i++))
            done

            sed -i "2s/.*/define(\"VERSION\", \"${tag}\");/" src/footer.php

            git add src/footer.php

            commit_message="Update version"
            if $psl_updated; then
              git add src/data/public-suffix-list.dat
              commit_message="${commit_message} and public-suffix-list.dat"
            fi
            if $rdap_updated; then
              git add src/data/rdap-servers-iana.json
              commit_message="${commit_message} and rdap-servers-iana.json"
            fi

            git commit -m "${commit_message}"
            git push

            git tag "${tag}"
            git push origin "${tag}"
          else
            echo "No updates detected."
          fi
