name: Update public-suffix-list.dat and rdap-servers-iana.json

on:
  schedule:
    - cron: "33 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: List tags
        run: git tag

      - name: Download files
        run: |
          curl -fsSL "https://publicsuffix.org/list/public_suffix_list.dat" -o src/data/public-suffix-list.dat
          curl -fsSL "https://data.iana.org/rdap/dns.json" -o src/data/rdap-servers-iana.json

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            base_tag="v$(date -u +%Y.%-m.%-d)"
            tag="${base_tag}"
            i=1
            while git rev-parse "${tag}" >/dev/null 2>&1; do
              tag="${base_tag}+${i}"
              ((i++))
            done

            sed -i "2s/.*/define(\"VERSION\", \"${tag}\");/" src/index.php

            git add src/index.php src/data/public-suffix-list.dat src/data/rdap-servers-iana.json
            git commit -m "Update version and public-suffix-list.dat and rdap-servers-iana.json"
            git push

            git tag "${tag}"
            git push origin "${tag}"
          else
            echo "No updates detected."
          fi
